CREATE TABLE IF NOT EXISTS TB_CATEGORIES (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TB_USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(100) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    ACTIVE TINYINT(1) DEFAULT 0,
    REQUESTED_AT DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TB_PRODUCTS (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(150) NOT NULL UNIQUE,
    CATEGORY_ID INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES TB_CATEGORIES(CATEGORY_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TB_PRODUCT_VARIANTS (
    VARIANT_ID BIGINT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    VARIANT_NAME VARCHAR(150) NOT NULL,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    STOCK_QUANTITY INT NOT NULL DEFAULT 0,
    UNIT_OF_MEASURE VARCHAR(50) NOT NULL DEFAULT 'piece',
    REORDER_POINT INT NOT NULL DEFAULT 5,
    FOREIGN KEY (PRODUCT_ID) REFERENCES TB_PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TB_TRANSACTIONS (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    TRANSACTION_DATE DATETIME NOT NULL,
    TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL,
    PAYMENT_METHOD VARCHAR(50) NOT NULL DEFAULT 'Cash',
    USER_ID INT NOT NULL,
    CLERK_NAME VARCHAR(100) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES TB_USERS(USER_ID) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TB_TRANSACTION_ITEMS (
    ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    TRANSACTION_ID INT NOT NULL,
    VARIANT_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE_AT_SALE DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (TRANSACTION_ID) REFERENCES TB_TRANSACTIONS(TRANSACTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (VARIANT_ID) REFERENCES TB_PRODUCT_VARIANTS(VARIANT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TB_STOCKIN_LOGS (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    VARIANT_ID BIGINT NOT NULL,
    QUANTITY_ADDED INT NOT NULL,
    DATE_LOGGED DATETIME NOT NULL,
    USER_ID INT NOT NULL,
    USER_NAME VARCHAR(100) NOT NULL,
    FOREIGN KEY (VARIANT_ID) REFERENCES TB_PRODUCT_VARIANTS(VARIANT_ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES TB_USERS(USER_ID) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TB_ACCOUNT_REQUESTS (
    REQUEST_ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    REQUEST_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'Pending',
    APPROVED_BY INT NULL,
    FOREIGN KEY (APPROVED_BY) REFERENCES TB_USERS(USER_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
